/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ClubMakingRouteImport } from './routes/club-making'
import { Route as FittingRouteImport } from './routes/fitting'
import { Route as GiftCardThanksRouteImport } from './routes/gift-card-thanks'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as LocationRouteImport } from './routes/location'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as ApiPaypalIpnRouteImport } from './routes/api/paypal-ipn'
import { Route as ApiStripeGiftWebhookRouteImport } from './routes/api/stripe-gift-webhook'
import { Route as GiftCardsIndexRouteImport } from './routes/gift-cards.index'
import { Route as GiftCardsCodeRouteImport } from './routes/gift-cards.$code'
import { Route as GiftCardsChar123codeChar125DotpngRouteImport } from './routes/gift-cards_.{$code}[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubMakingRoute = ClubMakingRouteImport.update({
  id: '/club-making',
  path: '/club-making',
  getParentRoute: () => rootRouteImport,
} as any)
const FittingRoute = FittingRouteImport.update({
  id: '/fitting',
  path: '/fitting',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardThanksRoute = GiftCardThanksRouteImport.update({
  id: '/gift-card-thanks',
  path: '/gift-card-thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalIpnRoute = ApiPaypalIpnRouteImport.update({
  id: '/api/paypal-ipn',
  path: '/api/paypal-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeGiftWebhookRoute = ApiStripeGiftWebhookRouteImport.update({
  id: '/api/stripe-gift-webhook',
  path: '/api/stripe-gift-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsIndexRoute = GiftCardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsCodeRoute = GiftCardsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => GiftCardsRoute,
} as any)
const GiftCardsChar123codeChar125DotpngRoute =
  GiftCardsChar123codeChar125DotpngRouteImport.update({
    id: '/gift-cards_/{$code}.png',
    path: '/gift-cards/{$code}.png',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/club-making': typeof ClubMakingRoute
  '/fitting': typeof FittingRoute
  '/gift-card-thanks': typeof GiftCardThanksRoute
  '/gift-cards': typeof GiftCardsRouteWithChildren
  '/location': typeof LocationRoute
  '/partners': typeof PartnersRoute
  '/studio': typeof StudioRoute
  '/trade-in': typeof TradeInRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/stripe-gift-webhook': typeof ApiStripeGiftWebhookRoute
  '/gift-cards/$code': typeof GiftCardsCodeRoute
  '/gift-cards/{$code}.png': typeof GiftCardsChar123codeChar125DotpngRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/club-making': typeof ClubMakingRoute
  '/fitting': typeof FittingRoute
  '/gift-card-thanks': typeof GiftCardThanksRoute
  '/location': typeof LocationRoute
  '/partners': typeof PartnersRoute
  '/studio': typeof StudioRoute
  '/trade-in': typeof TradeInRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/stripe-gift-webhook': typeof ApiStripeGiftWebhookRoute
  '/gift-cards/$code': typeof GiftCardsCodeRoute
  '/gift-cards/{$code}.png': typeof GiftCardsChar123codeChar125DotpngRoute
  '/gift-cards': typeof GiftCardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/club-making': typeof ClubMakingRoute
  '/fitting': typeof FittingRoute
  '/gift-card-thanks': typeof GiftCardThanksRoute
  '/gift-cards': typeof GiftCardsRouteWithChildren
  '/location': typeof LocationRoute
  '/partners': typeof PartnersRoute
  '/studio': typeof StudioRoute
  '/trade-in': typeof TradeInRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/stripe-gift-webhook': typeof ApiStripeGiftWebhookRoute
  '/gift-cards/$code': typeof GiftCardsCodeRoute
  '/gift-cards_/{$code}.png': typeof GiftCardsChar123codeChar125DotpngRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/club-making'
    | '/fitting'
    | '/gift-card-thanks'
    | '/gift-cards'
    | '/location'
    | '/partners'
    | '/studio'
    | '/trade-in'
    | '/api/paypal-ipn'
    | '/api/stripe-gift-webhook'
    | '/gift-cards/$code'
    | '/gift-cards/{$code}.png'
    | '/gift-cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/club-making'
    | '/fitting'
    | '/gift-card-thanks'
    | '/location'
    | '/partners'
    | '/studio'
    | '/trade-in'
    | '/api/paypal-ipn'
    | '/api/stripe-gift-webhook'
    | '/gift-cards/$code'
    | '/gift-cards/{$code}.png'
    | '/gift-cards'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/club-making'
    | '/fitting'
    | '/gift-card-thanks'
    | '/gift-cards'
    | '/location'
    | '/partners'
    | '/studio'
    | '/trade-in'
    | '/api/paypal-ipn'
    | '/api/stripe-gift-webhook'
    | '/gift-cards/$code'
    | '/gift-cards_/{$code}.png'
    | '/gift-cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  ClubMakingRoute: typeof ClubMakingRoute
  FittingRoute: typeof FittingRoute
  GiftCardThanksRoute: typeof GiftCardThanksRoute
  GiftCardsRoute: typeof GiftCardsRouteWithChildren
  LocationRoute: typeof LocationRoute
  PartnersRoute: typeof PartnersRoute
  StudioRoute: typeof StudioRoute
  TradeInRoute: typeof TradeInRoute
  ApiPaypalIpnRoute: typeof ApiPaypalIpnRoute
  ApiStripeGiftWebhookRoute: typeof ApiStripeGiftWebhookRoute
  GiftCardsChar123codeChar125DotpngRoute: typeof GiftCardsChar123codeChar125DotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club-making': {
      id: '/club-making'
      path: '/club-making'
      fullPath: '/club-making'
      preLoaderRoute: typeof ClubMakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitting': {
      id: '/fitting'
      path: '/fitting'
      fullPath: '/fitting'
      preLoaderRoute: typeof FittingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-card-thanks': {
      id: '/gift-card-thanks'
      path: '/gift-card-thanks'
      fullPath: '/gift-card-thanks'
      preLoaderRoute: typeof GiftCardThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-ipn': {
      id: '/api/paypal-ipn'
      path: '/api/paypal-ipn'
      fullPath: '/api/paypal-ipn'
      preLoaderRoute: typeof ApiPaypalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-gift-webhook': {
      id: '/api/stripe-gift-webhook'
      path: '/api/stripe-gift-webhook'
      fullPath: '/api/stripe-gift-webhook'
      preLoaderRoute: typeof ApiStripeGiftWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards/': {
      id: '/gift-cards/'
      path: '/'
      fullPath: '/gift-cards/'
      preLoaderRoute: typeof GiftCardsIndexRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards/$code': {
      id: '/gift-cards/$code'
      path: '/$code'
      fullPath: '/gift-cards/$code'
      preLoaderRoute: typeof GiftCardsCodeRouteImport
      parentRoute: typeof GiftCardsRoute
    }
    '/gift-cards_/{$code}.png': {
      id: '/gift-cards_/{$code}.png'
      path: '/gift-cards/{$code}.png'
      fullPath: '/gift-cards/{$code}.png'
      preLoaderRoute: typeof GiftCardsChar123codeChar125DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GiftCardsRouteChildren {
  GiftCardsCodeRoute: typeof GiftCardsCodeRoute
  GiftCardsIndexRoute: typeof GiftCardsIndexRoute
}

const GiftCardsRouteChildren: GiftCardsRouteChildren = {
  GiftCardsCodeRoute: GiftCardsCodeRoute,
  GiftCardsIndexRoute: GiftCardsIndexRoute,
}

const GiftCardsRouteWithChildren = GiftCardsRoute._addFileChildren(
  GiftCardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  ClubMakingRoute: ClubMakingRoute,
  FittingRoute: FittingRoute,
  GiftCardThanksRoute: GiftCardThanksRoute,
  GiftCardsRoute: GiftCardsRouteWithChildren,
  LocationRoute: LocationRoute,
  PartnersRoute: PartnersRoute,
  StudioRoute: StudioRoute,
  TradeInRoute: TradeInRoute,
  ApiPaypalIpnRoute: ApiPaypalIpnRoute,
  ApiStripeGiftWebhookRoute: ApiStripeGiftWebhookRoute,
  GiftCardsChar123codeChar125DotpngRoute:
    GiftCardsChar123codeChar125DotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
